name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Runs whenever the main branch is updated

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # Deploys to gh-pages branch
          folder: build      # Deploys the build folder
          token: ${{ secrets.GH_TOKEN }}  # Use the token from GitHub Secrets
